"""Create narratives table

Revision ID: 0003
Revises: 0002
Create Date: 2025-09-18 14:47:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('narratives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('narrative_type', sa.String(length=50), nullable=False),
    sa.Column('key_insights', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('sections', sa.Text(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('patterns', sa.Text(), nullable=True),
    sa.Column('csv_file_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('generation_method', sa.String(length=50), nullable=False),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('insights_count', sa.Integer(), nullable=False),
    sa.Column('patterns_count', sa.Integer(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['csv_file_id'], ['csv_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narratives_id'), 'narratives', ['id'], unique=False)
    op.create_index('ix_narratives_user_created', 'narratives', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_narratives_type', 'narratives', ['narrative_type'], unique=False)
    op.create_index('ix_narratives_favorite', 'narratives', ['is_favorite'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_narratives_favorite', table_name='narratives')
    op.drop_index('ix_narratives_type', table_name='narratives')
    op.drop_index('ix_narratives_user_created', table_name='narratives')
    op.drop_index(op.f('ix_narratives_id'), table_name='narratives')
    op.drop_table('narratives')
    # ### end Alembic commands ###