"""Create files table

Revision ID: 2c9a6f473a8a
Revises: bfaa8848f7e0
Create Date: 2025-09-14 17:55:30.224572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c9a6f473a8a'
down_revision = 'bfaa8848f7e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###